# Generated by Django 4.1.7 on 2023-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=260)),
                ('category', models.CharField(choices=[('abc', 'abc'), ('lki', 'lki'), ('mnk', 'mnk'), ('mhj', 'mhj')], default='abc', max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
