# Generated by Django 4.1.7 on 2023-03-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='markcompleted',
            field=models.BooleanField(default=False),
        ),
    ]
